services:
  db:
    image: mongo:7
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: song_user
      MONGO_INITDB_ROOT_PASSWORD: song_pass
      MONGO_INITDB_DATABASE: songs_db
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - songnet

  backend:
    build: ./backend
    restart: always
    environment:
      MONGO_HOST: db
      MONGO_PORT: 27017
      MONGO_DB: songs_db
      MONGO_USER: song_user
      MONGO_PASS: song_pass
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - songnet

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - songnet

volumes:
  mongodata:

networks:
  songnet:
