apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: song-manager
type: Opaque
data:
  MONGO_USER: dXNlcg==        # "user" base64
  MONGO_PASS: cGFzcw==        # "pass" base64
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
  namespace: song-manager
data:
  MONGO_DB: "testdb"
